package com.wh.mybatis.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.id
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_name
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    private String eName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_age
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    private Integer eAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_sex
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    private Integer eSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_department
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    private Integer eDepartment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.id
     *
     * @return the value of emp.id
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.id
     *
     * @param id the value for emp.id
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_name
     *
     * @return the value of emp.e_name
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_name
     *
     * @param eName the value for emp.e_name
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public void seteName(String eName) {
        this.eName = eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_age
     *
     * @return the value of emp.e_age
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public Integer geteAge() {
        return eAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_age
     *
     * @param eAge the value for emp.e_age
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public void seteAge(Integer eAge) {
        this.eAge = eAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_sex
     *
     * @return the value of emp.e_sex
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public Integer geteSex() {
        return eSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_sex
     *
     * @param eSex the value for emp.e_sex
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public void seteSex(Integer eSex) {
        this.eSex = eSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_department
     *
     * @return the value of emp.e_department
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public Integer geteDepartment() {
        return eDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_department
     *
     * @param eDepartment the value for emp.e_department
     *
     * @mbg.generated Sun Apr 11 18:06:47 CST 2021
     */
    public void seteDepartment(Integer eDepartment) {
        this.eDepartment = eDepartment;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", eName='" + eName + '\'' +
                ", eAge=" + eAge +
                ", eSex=" + eSex +
                ", eDepartment=" + eDepartment +
                '}';
    }
}